# Generated by Django 4.1.7 on 2023-03-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bookingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='lname',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
