# Generated by Django 4.1.7 on 2023-04-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_bookingmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
