# Generated by Django 4.1.7 on 2023-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_bookingmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
