# Generated by Django 4.1.7 on 2023-04-21 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_bookingmodel_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='')),
                ('pub_date', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.CharField(default='Priyanka', max_length=150)),
                ('readtime', models.IntegerField()),
            ],
        ),
    ]
