# Generated by Django 4.1.7 on 2023-03-22 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_appointmentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='contact',
        ),
    ]
