# Generated by Django 4.1.7 on 2023-05-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_addblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicesmodel'),
        ),
    ]
