# Generated by Django 4.1.7 on 2023-05-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_bookingmodel_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='services',
        ),
    ]
