# Generated by Django 4.1.7 on 2023-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_bookingmodel_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='product',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='bookingmodel',
            old_name='price',
            new_name='prices',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='services',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
