# Generated by Django 4.1.7 on 2023-05-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_bookingmodel_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.servicesmodel'),
            preserve_default=False,
        ),
    ]
