# Generated by Django 4.1.7 on 2023-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_name_bookingmodel_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='datentime',
            field=models.DateField(default='2023-03-29'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='state',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='zip',
            field=models.IntegerField(default=256325),
            preserve_default=False,
        ),
    ]
