# Generated by Django 4.1.7 on 2023-05-03 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_bookingmodel_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='amount',
        ),
    ]
