# Generated by Django 4.1.7 on 2023-03-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_bookingmodel_city_bookingmodel_datentime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='username',
        ),
    ]
