# Generated by Django 4.1.7 on 2023-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_bookingmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='prices',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
