# Generated by Django 4.1.7 on 2023-03-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_bookingmodel_prices_bookingmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='datentime',
            field=models.DateTimeField(),
        ),
    ]
