# Generated by Django 4.1.7 on 2023-03-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_bookingmodel_datentime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='datentime',
            field=models.DateField(),
        ),
    ]
