# Generated by Django 4.1.7 on 2023-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_bookingmodel_datentime'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='prices',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
