# Generated by Django 4.1.7 on 2023-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_servicesmodel_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
