# Generated by Django 4.1.7 on 2023-04-01 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_bookingmodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddToCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.servicesmodel')),
            ],
        ),
    ]
